### ISSUE TITLE
How to create an intelligent contract at hcash? 

### ISSUE THREAD

**Issue by nisang** [HcashOrg/Hcash#8]
How to create an intelligent contract at hcash? No relevant technical documents have been found。

**Comment by zoowii** [comment]
[https://github.com/HcashOrg/Hcash/wiki/Smart-Contract-Guide](https://github.com/HcashOrg/Hcash/wiki/Smart-Contract-Guide)

This is a simple smart contract guide in HCash. More documents will be published later.

**Comment by nisang** [comment]
According to the document provided above, run two command lines and display the following information：
-- compile_contract the-contract-source-path
`compile_contract hello.glua`

-- register_contract caller-account-name path-of-contract-gpc-file system-asset-symbol gasLimit
`register_contract nisang hello.gpc HSR 0.000001`

error ： _20010 insufficient_funds: insufficient funds_；

How do I get the HSR I need

**Comment by nisang** [comment]
Can you provide an automatic URL link for tokens, like qtum officials, using an intelligent contract to automatically test the tokens

**Comment by yusun** [comment]
you can mining HSR through set_generate true 1  ps: 1 is thread pool count.
you can import old hshare private key which already have money.
you can offer one address, and then i will transfer some to you

**Comment by zoowii** [comment]
@nisang [https://github.com/HcashOrg/Hcash/wiki/Token-Contract-Sample](https://github.com/HcashOrg/Hcash/wiki/Token-Contract-Sample)   is the wiki page of token contract
