### ISSUE TITLE
which api for exporting a wallet account private key?

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/Hcash#9]
which api for exporting a wallet account private key, not backup wallet.

**Comment by yusun** [comment]
wallet_dump_account_private_key account_name 0
wallet_backup_create filepath   
wallet_backup_restore filepath wallet_name wallet_passphrase

**Comment by chengxulvtu** [comment]
@yusun I export account private key in GUI hcash wallet ,the result looks like `EAC118D1ABF7247D642E15A5D5D4DE24AE6B7BBB44CA0AD5A1CAA4799EE8BD9AA07DA23DF3A330939DA6E3307CC9EF991674CB4F4A9FD330D04B27BF31A63D6E`
But I exec the command 'wallet_backup_create', the result as as follows `[
{
  "type": "master_key_entry_type",
  "data": {
    "index": -1,
    "encrypted_key": "6670deda18358b69058f7afd825a19f7bf93167e4fbb9073437f525a47870dcc9e612e8e8a358070cdd85212494b3dfd94e68016537e0eeb1f172cb69bbee969e01420152e933083f1dcbde16370a8b7",
    "checksum": "cfe3fa3e721b9bf854193dfd8ba90f34bab78348cca90b7c62659772dfc751cf906e90400bc6c5c680f8355c4172a0583021a823be1e37b29d777059029b35df"
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 1,
    "key": "next_entry_number",
    "value": 13
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 2,
    "key": "version",
    "value": 109
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 3,
    "key": "automatic_backups",
    "value": true
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 4,
    "key": "transaction_scanning",
    "value": true
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 5,
    "key": "last_unlocked_scanned_block_number",
    "value": 21165
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 6,
    "key": "last_scanned_block_number_for_hsrcore",
    "value": 21165
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 7,
    "key": "default_transaction_priority_fee",
    "value": {
      "amount": 1,
      "asset_id": 0
    }
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 8,
    "key": "transaction_expiration_sec",
    "value": 3600
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 9,
    "key": "transaction_min_imessage_fee_coe",
    "value": 100
  }
},
{
  "type": "property_entry_type",
  "data": {
    "index": 10,
    "key": "transaction_min_imessage_soft_length",
    "value": 40
  }
},
{
  "type": "account_entry_type",
  "data": {
    "index": 11,
    "id": 0,
    "name": "abc0",
    "public_data": null,
    "owner_key": "H6sDQtRD6N5M3ZuH61htkyE8LX6BSS1cnPxWWzXReafb6ozvF1H",
    "active_key_history": [[
        "2017-12-17T17:51:54",
        "H6sDQtRD6N5M3ZuH61htkyE8LX6BSS1cnPxWWzXReafb6ozvF1H"
      ]
    ],
    "registration_date": "1970-01-01T00:00:00",
    "last_update": "2017-12-17T17:51:54",
    "is_my_account": true,
    "approved": 0,
    "is_favorite": false,
    "block_production_enabled": false,
    "last_used_gen_sequence": 0,
    "private_data": null
  }
},
{
  "type": "key_entry_type",
  "data": {
    "index": 12,
    "account_address": "HLHmY8pjxbLbgpFG6wQu5wfx6xMkfdyh76",
    "public_key": "H6sDQtRD6N5M3ZuH61htkyE8LX6BSS1cnPxWWzXReafb6ozvF1H",
    "encrypted_private_key": "76e0d7386afc36743095573707e723aba91afb122650dd7141c4b821f2a6e2b6483ddb51f4e3426908fc6b0bc17b4f2d",
    "valid_from_signature": false,
    "gen_seq_number": 0
  }
}
]`
So I can't import the private key in GUI hcash wallet.

**Comment by chengxulvtu** [comment]
@yusun  I can't import the old .dat file in GUI hcash wallet, so I import .dat file using the command `wallet_import_hshare_private_key`. Then I export a account private key and import the private key in GUI hcash wallet.

**Comment by zoowii** [comment]
the private key exported from GUI hcash wallet is encrypted by the GUI wallet. It can only be imported via GUI HCash wallets. And the private key exported from HCash command-line wallet is a plain text private key.

**Comment by chengxulvtu** [comment]
@zoowii  So how do I get the test token in  the GUI Hcash wallet?

**Comment by zoowii** [comment]
you can mining HSR through set_generate true 1 ps: 1 is thread pool count.
you can import old hshare private key which already have money.
you can offer one address, and then i will transfer some to you.

**Comment by chengxulvtu** [comment]
@zoowii  Please transfer some tokens to `HsRKuehwHLyEXb4nVwkoDgL8xrGqr4phpjY` . Thanks very much.

**Comment by yusun** [comment]
your address is an invalid address . please offer a valid address such like HNNCAkXtTiNV68uWsCyXH6JuT4awYDa9b4  .

**Comment by chengxulvtu** [comment]
我还是说中文吧。

请问这个项目里的Hcash wallet 和 hcashd 项目里的hcash wallet有什么不一样？

**Comment by bitoo** [comment]
现在hsr采用多方案并行处理，也就是说那种方案更好用哪种，所有的解释权归基金会




 
From: Bob Tian
Date: 2017-12-19 13:43
To: HcashOrg/Hcash
CC: Subscribed
Subject: Re: [HcashOrg/Hcash] which api for exporting a wallet account private key? (#9)
我还是说中文吧。
请问这个项目里的Hcash wallet 和 hcashd 项目里的hcash wallet有什么不一样？

**Comment by chengxulvtu** [comment]
好的，了解了
